server:
  port: 8080
  servlet:
    context-path: /market
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demodb
    username: root
    password: root
  kafka:
    bootstrap-servers: 192.168.2.200:9092,192.168.2.201:9092,192.168.2.202:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      auto-offset-reset: latest
      group-id: group1
      max-poll-records: 100
      auto-commit-interval: 1000ms
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    template:
      default-topic: market
    listener:
      poll-timeout: 15000ms

mybatis:
  mapper-locations: classpath*:mapper/UserMapper.xml
